# Generated by Django 2.2.5 on 2020-05-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('united kingdom', 'United Kingdom'), ('united states', 'United States'), ('france', 'France'), ('germany', 'Germany')], max_length=40),
        ),
    ]
